"""Launch-command builder — adapter-driven, one path for every runtime.

argv = [bin] + permission_flags(posture) + model_flags + effort_flags.

Two shapes:

  * Plain / no persona -> command = shlex.join(argv), no temp launcher. The
    whole command is a flat argv with nothing multiline, so it crosses the
    agent->tfork shell boundary safely once shell-quoted.

  * Custom WITH persona (codex/claude) -> the persona is a large multiline body
    with embedded quotes / ``#``. Putting it on the command line would force the
    *calling agent* to quote it through its own shell when invoking tfork. So we
    write a controlled temp launcher: the raw persona goes to a 0600 payload, and
    a tiny launch.sh reads it back with ``$(cat …)`` inside its own shell. The
    only thing crossing the boundary is a short ``bash <launcher>`` — shlex-quoted
    so a temp path with spaces/metacharacters can't break out.

Permission enforcement stays on the *flags* (e.g. codex ``--sandbox``), never on
prompt text.
"""

import os
import shlex
import tempfile
from pathlib import Path


def _persona_tail(style, flag):
    """Render the launcher's persona-injection line for the adapter's declared
    style. The 0600 payload always lives at ``$DIR/persona.txt``. The adapter
    owns which shape applies; launch.py only knows how to render each style.
    """
    if style == "config_cat":   # codex:  -c key="$(cat payload)"
        return f'-c {flag}="$(cat "$DIR/persona.txt")"'
    if style == "flag_cat":     # claude: --flag "$(cat payload)"
        return f'{flag} "$(cat "$DIR/persona.txt")"'
    if style == "flag_path":    # pi:     --flag <payload-path>
        return f'{flag} "$DIR/persona.txt"'
    raise ValueError(f"unknown persona_inject style {style!r}")


def build_launch(adapter, agent, posture, model, effort, persona, root=None):
    """Return (command_str, workdir). ``persona`` is the persona body (or empty
    for plain agents). ``root`` is injectable for tests."""
    argv = [adapter.bin]
    argv += adapter.permission_flags(posture)
    if model:
        argv += adapter.model_flag(model)
    if effort:
        argv += adapter.effort_flag(effort)

    persona = persona or ""
    if not persona:
        # Plain / no persona: a flat, safe argv. No temp launcher.
        return shlex.join(argv), None

    # Custom with persona: payload + generated launch.sh.
    safe = "".join(c if c.isalnum() or c in "-_" else "_" for c in (agent or "agent"))
    if root is None:
        root = tempfile.mkdtemp(prefix=f"afork-{safe}-")
    workdir = Path(root)
    workdir.mkdir(parents=True, exist_ok=True)

    payload = workdir / "persona.txt"
    payload.write_text(persona)
    os.chmod(payload, 0o600)

    # The persona-injection SHAPE is the adapter's call, not launch.py's — we
    # only render the style it declares. (No sniffing the flag spelling.)
    inject = adapter.persona_inject
    style, flag = inject["style"], inject["flag"]
    tail = _persona_tail(style, flag)

    head = " ".join(shlex.quote(tok) for tok in argv)
    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "# Generated by afork. Launches the agent with its permission posture",
        "# enforced via flags and its persona injected from a 0600 payload.",
        'DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"',
        f'exec {head} \\',
        f'  {tail}',
    ]

    launcher = workdir / "launch.sh"
    launcher.write_text("\n".join(lines) + "\n")
    os.chmod(launcher, 0o700)

    # tfork pastes this string into an interactive shell, so it is shell syntax
    # — not a safe argv array. shlex.join quotes the launcher path so a temp
    # root containing spaces or shell metacharacters can't break out.
    command = shlex.join(["bash", str(launcher)])
    return command, str(workdir)
