"""Launch-command builder — adapter-driven, one path for every runtime.

argv = [bin] + permission_flags(posture) + model_flags + effort_flags.

Two shapes:

  * Plain / no persona -> command = shlex.join(argv), no temp launcher. The
    whole command is a flat argv with nothing multiline, so it crosses the
    agent->tfork shell boundary safely once shell-quoted.

  * Custom WITH persona (codex/claude) -> the persona is a large multiline body
    with embedded quotes / ``#``. Putting it on the command line would force the
    *calling agent* to quote it through its own shell when invoking tfork. So we
    write a controlled temp launcher: the raw persona goes to a 0600 payload, and
    a tiny executable launch.sh reads it back with ``$(cat …)`` inside its own
    shell. The only thing crossing the boundary is the launcher path —
    shlex-quoted so a temp path with spaces/metacharacters can't break out.

Permission enforcement stays on the *flags* (e.g. codex ``--sandbox``), never on
prompt text.

Observability (opt-in) wraps whichever shape applies with ``lens run --`` and
carries attribution through ``AGENTLENS_TAGS`` in the child environment (env
beats agentlens's own ``--tag`` flags on collision, so the outer orchestrator's
attribution survives nested spawns). Wrapping is decided upstream — by the time
build_launch sees ``observe`` it is already known that ``lens`` is on PATH.

Both shapes get the private workdir, because both get a 0600 *launch-contract
sidecar*: afork is the side that knows which runtime and model were really
invoked and what that runtime's failure output looks like, so it writes that
down for tfork instead of tfork guessing. The generated launcher additionally
carries the contract-bound exec-failure marker — see ``_launcher_lines``.
"""

import os
import secrets
import shlex
import tempfile
from collections import namedtuple
from pathlib import Path

from .outcome import build_sidecar, exec_marker, write_sidecar

# What build_launch hands back: the command tfork forks, afork's private
# workdir, the sidecar path tfork reads, and the id tying them together.
Launch = namedtuple("Launch", "command workdir launch_contract attempt_id")


def _tag_string(obs_tags):
    """Render tags into the AGENTLENS_TAGS wire format (``k=v,k2=v2``), or ''
    when there are none. Insertion order is preserved."""
    return ",".join(f"{k}={v}" for k, v in (obs_tags or {}).items())


def _persona_tail(style, flag):
    """Render the launcher's persona-injection line for the adapter's declared
    style. The 0600 payload always lives at ``$DIR/persona.txt``. The adapter
    owns which shape applies; launch.py only knows how to render each style.
    """
    if style == "config_cat":   # codex:  -c key="$(cat payload)"
        return f'-c {flag}="$(cat "$DIR/persona.txt")"'
    if style == "flag_cat":     # claude: --flag "$(cat payload)"
        return f'{flag} "$(cat "$DIR/persona.txt")"'
    if style == "flag_path":    # pi:     --flag <payload-path>
        return f'{flag} "$DIR/persona.txt"'
    raise ValueError(f"unknown persona_inject style {style!r}")


def _launcher_lines(head, tail, tags, observe, marker):
    """Render the generated launch.sh.

    The runtime is attempted EXACTLY ONCE, with ``exec``. On success the shell
    is replaced and nothing below the exec line can ever run — which is what
    makes ``marker`` trustworthy: it is physically unreachable unless that one
    real exec failed. ``shopt -s execfail`` is what lets the script survive a
    failed exec to print it (bash would otherwise abort), and ``set -e`` is
    deliberately absent for the same reason — with it, the failed exec's status
    would kill the script one line before the marker.

    There is no retry, no probe, and no second attempt: a launcher that tried
    the runtime twice would make the marker mean "both attempts failed", which
    is not what the contract promises.

    Under --observe the exec target is ``lens``, not the runtime, so a missing
    *runtime* binary is reported by lens rather than by exec failing. That case
    simply does not reach the marker and stays ``unknown`` — an observability
    wrapper must not be able to manufacture a trusted failure classification.
    """
    lines = [
        "#!/usr/bin/env bash",
        "set -uo pipefail",
        "shopt -s execfail",
        "# Generated by afork. Launches the agent with its permission posture",
        "# enforced via flags and its persona injected from a 0600 payload.",
        'DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"',
    ]
    if tags:
        # Exported so the tags reach `lens run` *and* anything the agent itself
        # spawns — inherited env is what keeps nested spawns attributed.
        lines.append(f"export AGENTLENS_TAGS={shlex.quote(tags)}")
    lines += [
        f'exec {"lens run -- " if observe else ""}{head} \\',
        f'  {tail}',
        "__afork_ec=$?",
        "# Only reachable when the single exec above failed: the runtime is",
        "# missing or not executable. This marker is the contract's evidence.",
        f"printf '\\n{marker}\\n'",
        'exit "$__afork_ec"',
    ]
    return lines


def build_launch(adapter, agent, posture, model, effort, persona, root=None,
                 observe=False, obs_tags=None, attempt_id=None):
    """Return a ``Launch``. ``persona`` is the persona body (or empty for plain
    agents). ``root`` and ``attempt_id`` are injectable for tests. ``observe``
    wraps the runtime invocation in ``lens run --``; ``obs_tags`` is the
    attribution dict carried to it through AGENTLENS_TAGS."""
    argv = [adapter.bin]
    argv += adapter.permission_flags(posture)
    if model:
        argv += adapter.model_flag(model)
    if effort:
        argv += adapter.effort_flag(effort)

    tags = _tag_string(obs_tags) if observe else ""
    persona = persona or ""
    attempt_id = attempt_id or secrets.token_hex(8)

    safe = "".join(c if c.isalnum() or c in "-_" else "_" for c in (agent or "agent"))
    if root is None:
        root = tempfile.mkdtemp(prefix=f"afork-{safe}-")
    workdir = Path(root)
    workdir.mkdir(parents=True, exist_ok=True)

    # The sidecar is written for BOTH shapes. Only the launcher shape can emit
    # the exec marker, so the plain shape records exec_marker=null rather than
    # advertising evidence it can never produce.
    sidecar = build_sidecar(
        attempt_id, adapter.runtime, agent, model, effort,
        getattr(adapter, "launch_signatures", None),
        has_launcher=bool(persona))
    contract_path = write_sidecar(workdir, sidecar)

    if not persona:
        # Plain / no persona: a flat, safe argv. No temp launcher.
        if observe:
            argv = ["lens", "run", "--"] + argv
            if tags:
                # `env VAR=… cmd` keeps the whole thing one flat argv — no shell
                # assignment syntax, so it survives shlex.join unchanged.
                argv = ["env", f"AGENTLENS_TAGS={tags}"] + argv
        return Launch(shlex.join(argv), str(workdir), contract_path, attempt_id)

    # Custom with persona: payload + generated launch.sh.
    payload = workdir / "persona.txt"
    payload.write_text(persona)
    os.chmod(payload, 0o600)

    # The persona-injection SHAPE is the adapter's call, not launch.py's — we
    # only render the style it declares. (No sniffing the flag spelling.)
    inject = adapter.persona_inject
    style, flag = inject["style"], inject["flag"]
    tail = _persona_tail(style, flag)
    head = " ".join(shlex.quote(tok) for tok in argv)

    launcher = workdir / "launch.sh"
    launcher.write_text("\n".join(_launcher_lines(
        head, tail, tags, observe, exec_marker(attempt_id))) + "\n")
    os.chmod(launcher, 0o700)

    # tfork pastes this string into an interactive shell, so it is shell syntax
    # — not a safe argv array. The launcher is executable; returning just that
    # one path avoids a `bash <launcher>` string becoming a literal filename if
    # a caller passes the handoff command to tfork as one argv token.
    return Launch(shlex.join([str(launcher)]), str(workdir), contract_path,
                  attempt_id)
